FROM submitty-python-worker:latest

ENV COVERAGE_FILE /buildbot/python-migrations-tests/build/autograder/.coverage.autograder

USER buildbot
WORKDIR /buildbot

CMD ["/usr/bin/dumb-init", "twistd", "--pidfile=", "-ny", "buildbot.tac"]