FROM submitty-python-worker:latest

ENV COVERAGE_FILE /buildbot/python-migrations-tests/build/migration/.coverage.migrator

USER buildbot
WORKDIR /buildbot

CMD ["/usr/bin/dumb-init", "twistd", "--pidfile=", "-ny", "buildbot.tac"]

